name: mmoTarget
version: ${releaseVersion}.${buildNumber}
description: Provides a visible target display, including health, pet's owner and target's target.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Target.MMOTarget
depend: [Spout, mmoCore]
