name: mmoTarget
main: mmo.Target.MMOTarget
version: 1.3
website: http://forums.bukkit.org/threads/31056/
author: Rycochet <rycochet@rycochet.com>
depend: [Spout,mmoCore]

description: Lets you target an enemy (or friend) showing their health on the screen.
